package ap.panini.kwhen.en

import ap.panini.kwhen.DayOfWeek
import ap.panini.kwhen.TimeUnit

internal val months = mapOf(
    "january" to 1,
    "jan." to 1,
    "jan" to 1,
    "february" to 2,
    "feb." to 2,
    "feb" to 2,
    "march" to 3,
    "mar." to 3,
    "mar" to 3,
    "apr." to 4,
    "apr" to 4,
    "may" to 5,
    "june" to 6,
    "jun." to 6,
    "jun" to 6,
    "july" to 7,
    "jul." to 7,
    "jul" to 7,
    "august" to 8,
    "aug." to 8,
    "aug" to 8,
    "sept." to 9,
    "sept" to 9,
    "september" to 9,
    "sep." to 9,
    "sep" to 9,
    "october" to 10,
    "oct." to 10,
    "oct" to 10,
    "november" to 11,
    "nov." to 11,
    "nov" to 11,
    "december" to 12,
    "dec." to 12,
    "dec" to 12,
)

internal val ordinal = mapOf(
    "first" to 1,
    "second" to 2,
    "third" to 3,
    "fourth" to 4,
    "fifth" to 5,
    "sixth" to 6,
    "seventh" to 7,
    "eighth" to 8,
    "ninth" to 9,
    "tenth" to 10,
    "eleventh" to 11,
    "twelfth" to 12,
    "thirteenth" to 13,
    "fourteenth" to 14,
    "fifteenth" to 15,
    "sixteenth" to 16,
    "seventeenth" to 17,
    "eighteenth" to 18,
    "nineteenth" to 19,
    "twentieth" to 20,
    "twenty first" to 21,
    "twenty-first" to 21,
    "twenty second" to 22,
    "twenty-second" to 22,
    "twenty third" to 23,
    "twenty-third" to 23,
    "twenty fourth" to 24,
    "twenty-fourth" to 24,
    "twenty fifth" to 25,
    "twenty-fifth" to 25,
    "twenty sixth" to 26,
    "twenty-sixth" to 26,
    "twenty seventh" to 27,
    "twenty-seventh" to 27,
    "twenty eighth" to 28,
    "twenty-eighth" to 28,
    "twenty ninth" to 29,
    "twenty-ninth" to 29,
    "thirtieth" to 30,
    "thirty first" to 31,
    "thirty-first" to 31,
)

internal val weekdays = mapOf(
    "monday" to DayOfWeek.MONDAY,
    "mon." to DayOfWeek.MONDAY,
    "mon" to DayOfWeek.MONDAY,
    "tuesday" to DayOfWeek.TUESDAY,
    "tues." to DayOfWeek.TUESDAY,
    "tues" to DayOfWeek.TUESDAY,
    "tue." to DayOfWeek.TUESDAY,
    "tue" to DayOfWeek.TUESDAY,
    "wednesday" to DayOfWeek.WEDNESDAY,
    "wens." to DayOfWeek.WEDNESDAY,
    "wens" to DayOfWeek.WEDNESDAY,
    "wed." to DayOfWeek.WEDNESDAY,
    "wed" to DayOfWeek.WEDNESDAY,
    "wen." to DayOfWeek.WEDNESDAY,
    "wen" to DayOfWeek.WEDNESDAY,
    "thursday" to DayOfWeek.THURSDAY,
    "thurs." to DayOfWeek.THURSDAY,
    "thurs" to DayOfWeek.THURSDAY,
    "thu." to DayOfWeek.THURSDAY,
    "thu" to DayOfWeek.THURSDAY,
    "friday" to DayOfWeek.FRIDAY,
    "fri." to DayOfWeek.FRIDAY,
    "fri" to DayOfWeek.FRIDAY,
    "saturday" to DayOfWeek.SATURDAY,
    "sat" to DayOfWeek.SATURDAY,
    "sat." to DayOfWeek.SATURDAY,
    "sunday" to DayOfWeek.SUNDAY,
    "sun." to DayOfWeek.SUNDAY,
    "sun" to DayOfWeek.SUNDAY,
)

internal val generalTimes = mapOf(
    "days" to TimeUnit.DAY,
    "day" to TimeUnit.DAY,
    "months" to TimeUnit.MONTH,
    "month" to TimeUnit.MONTH,
    "week" to TimeUnit.WEEK,
    "weeks" to TimeUnit.WEEK,
    "years" to TimeUnit.YEAR,
    "year" to TimeUnit.YEAR,
    "yrs" to TimeUnit.YEAR,
    "yr" to TimeUnit.YEAR,
    "hrs" to TimeUnit.HOUR,
    "hr" to TimeUnit.HOUR,
    "hours" to TimeUnit.HOUR,
    "hour" to TimeUnit.HOUR,
    "secs" to TimeUnit.SECOND,
    "sec" to TimeUnit.SECOND,
    "seconds" to TimeUnit.SECOND,
    "second" to TimeUnit.SECOND,
    "mins" to TimeUnit.MINUTE,
    "min" to TimeUnit.MINUTE,
    "minutes" to TimeUnit.MINUTE,
    "minute" to TimeUnit.MINUTE,
)

internal val amounts = mapOf(
    "a" to 1,
    "one" to 1,
    "two" to 2,
    "three" to 3,
    "four" to 4,
    "five" to 5,
    "six" to 6,
    "seven" to 7,
    "eight" to 8,
    "nine" to 9,
    "ten" to 10
)